Refactoring. (#8)
* The sync feature is complete.

* Started the build feature; proper flag handling in main

* Added boilerplate for all commands in main

*   On branch development
  Changes to be committed:
	modified:   repotools

  Added add/remove packafe features
  Refined the new repo feature
  Started working on the build feature
  Added the option to build all packages from all repositories

* Added function for automatically handling the sourcing of repository
config files.
Worked a little bit on the build function.

* Mostly code cleaning
Removed most cd lines, adapted the code accordingly(did not remove the
cd in the build command).
Added a new flag(N) that creates a new repository and opens it's config
file in vim.

* Testing, added more features
Finished all build features
Tested all features(that are currently implemented)

* Added update feature; need to test everything

* Update feature, refactoring and updated .gitignore

- Added the update feature, fixes #3
- Created a refactored file structure that allows better code management
- Updated the gitignore so that it now serves the current directory
status

* Refactored file structure
- grouped all functionalities in ./script_files/
- added a section that checks all the script files and sources them

* Refactored all flags and some variables
* Changed the flags in the main function and sorted them A->Z, along with comments regarding what each flag does.
* Renamed config variables to better reflect what they store
* Renamed local variables in functions for more consistency

diff --git a/repotools b/repotools
--- a/repotools
+++ b/repotools
@@ -1,138 +1,22 @@
 #!/bin/bash
 
-# Load the configuration file
 
-if [ ! -f .config ]; then
-  echo "Config file not found."
+# Load the script files
+
+if [[ ! -d "script_files" ]]; then
+  echo "The folder with the script files could not be found."
   exit 1
 fi
 
-source .config
+script_files=("script_files/.config" "script_files/add_remove_packages.sh" "script_files/build_environment.sh" "script_files/build_packages.sh" "script_files/help_usage.sh" "script_files/new_meta_package.sh" "script_files/new_repository.sh" "script_files/pacman_entries.sh" "script_files/sync_repositories.sh" "script_files/update_repositories.sh" "script_files/utils.sh")
 
-# ----------
-
-
-
-# Help&usage
-
-function print_help() {
-  echo
-}
-
-function print_usage() {
-  echo
-}
-
-# ----------
-
-
-
-# Commands
-
-function new_repository() {
-  local NAME="$1"; shift
-
-  cd "${GLOBAL_REPO_DIR}"
-
-  if [[ -d "${NAME}" ]]; then
-    echo "The repository already exists."
-  else
-    git clone https://github.com/cezarmathe/example_repository.git "${NAME}"
-
-    # TODO: change config file to match the repo name and other config variables
+for item in ${script_files[*]}; do
+  if [ ! -f "${item}" ]; then
+    echo "${item} file not found."
+    exit 1
   fi
-  
-}
-
-function initialize_build_environment() {
-  local DIR="$1"; shift
-
-  if [[ -z "${DIR}" ]]; then
-    mkdir -p "${GLOBAL_BUILD_DIR}"
-    mkarchroot -C /etc/pacman.conf "${GLOBAL_BUILD_DIR}/root" base-devel
-  else
-    if [[ "${DIR:0:1}" = "/" ]]; then
-      mkdir -p "${DIR}"
-      mkarchroot -C /etc/pacman.conf "${DIR}/root" base-devel
-    else
-      mkdir -p "${REPOTOOLS_PATH}/${DIR}"
-      mkarchroot -C /etc/pacman.conf "${REPOTOOLS_PATH}/${DIR}}/root" base-devel
-    fi
-  fi
-}
-
-function sync_with_remote() {
-  local REPO_NAME="$1"; shift
-
-  if [[ ! -z "${REPO_NAME}" ]]; then
-    # sync a single repository
-    cd "${GLOBAL_REPO_DIR}"
-    if [[ ! -d "${REPO_NAME}" ]]; then
-      echo "Repository ${REPO_NAME} does not exist."
-    else
-      cd "${REPO_NAME}"
-
-      if [[ ! -f ".config" ]]; then
-        echo "The repository ${REPO_NAME} has no config file."
-      else
-        source ./.config
-
-        # Check local configuration to create a final address for pulling and pushing to this repository
-        local ADDRESS=""
-        if [[ ! -z "${LOCAL_REMOTE_USER}" ]]; then
-          ADDRESS="${LOCAL_REMOTE_USER}@"
-        else
-          ADDRESS="${GLOBAL_REMOTE_USER}@"
-        fi
-
-        if [[ ! -z "${LOCAL_REMOTE_ADDRESS}" ]]; then
-          ADDRESS+="${LOCAL_REMOTE_ADDRESS}"
-        else
-          ADDRESS+="${GLOBAL_REMOTE_ADDRESS}"
-        fi
-
-        if [[ ! -z "${LOCAL_REMOTE_PORT}" ]]; then
-          ADDRESS+=":${LOCAL_REMOTE_PORT}"
-        fi
-
-        if [[ -z "${LOCAL_REMOTE_ENDPOINT}" ]]; then
-          echo "The repository ${REPO_NAME} does not have a remote endpoint specified in its configuration file."
-          return
-        fi
-
-        ADDRESS+="/${LOCAL_REMOTE_ENDPOINT}"
-
-        git fetch "${ADDRESS}"
-
-        local UPSTREAM=${1:-'@{u}'}
-        local LOCAL=$(git rev-parse @)
-        local REMOTE=$(git rev-parse "$UPSTREAM")
-        local BASE=$(git merge-base @ "$UPSTREAM")
-
-        if [ $LOCAL = $REMOTE ]; then
-            echo "The repository ${REPO_NAME} is up to date."
-        elif [ $LOCAL = $BASE ]; then
-            echo "${REPO_NAME} is not up to date with the remote, pulling the changes.."
-
-            git pull "${ADDRESS}" master
-
-        elif [ $REMOTE = $BASE ]; then
-            echo "${REPO_NAME} is ahead of the remote, pushing the changes.."
-
-            git add *
-            git commit -m "$(date)"
-            git push "${ADDRESS}" master
-        else
-            echo "${REPO_NAME} and the remote are diverged."
-        fi
-      fi
-    fi
-  else
-    echo "wip"
-    # sync all repositories
-
-  fi
-}
+  source "${item}"
+done
 
 # ----------
 
@@ -141,72 +25,185 @@ function sync_with_remote() {
 # Main cli
 
 function main() {
-  # local REPOSITORY="$1"; shift
 
-  # if [[ -z "$SUBCOMMAND" ]]; then
-  #   echo "No subcommand specified. Run \"./repotools help\" if you need help."
-  #   exit 1
-  # fi
-
-  while getopts 'n:a:r:sS:bB:ucm:iI:' flag; do
+  while getopts 'N:n:a:r:sSbB:guUcm:iI:' flag; do
     case "${flag}" in
-      n)
-        # new repository
-        new_repository "${OPTARG}"
-        ;;
-      a)
-        # add a new package in the repository
-        ;;
-      r)
-        # remove the package from the repository
-        ;;
-      s)
-        # sync all the repositories with the remote
-        sync_with_remote
-        ;;
-      S)
-        # sync a repository with the remote
-        sync_with_remote "${OPTARG}"
-        ;;
-      u)
-        # update the packages in the repository
-        ;;
-      c)
-        # do a cycle
-        ;;
+
+      A)
+        # Add a new package: -A <package_name> <repo_name> 
+        flag_add=1
+        arg_add="${OPTARG}"
+        shift 2;;
+
+      d)
+        # Build all packages within all repositories: -d
+        flag_build_all=1
+        shift;
+
       b)
-        # build all packages in a repository
-        ;;
+        # Build all packages within a single repository: -b <repo_name>
+        flag_build=1
+        shift;;
+
       B)
-        # build a package in a repository
-        ;;
-      m)
-        # create a new meta package in the repository
-        ;;
+        # Build a package: -B <package_name> <repo_name>
+        flag_build=1
+        arg_build="${OPTARG}"
+        shift 2;;
+
+      c)
+        # Cycle: -c
+        flag_cycle=1
+        shift;;
+
+      g)
+        # Generate a pacman entry for all repositories: -g
+        flag_generate_pacman_entry=1
+        shift;
+
+      G)
+        # Generate a pacman entry for a single repository: -G <repo_name>
+        flag_Generate_pacman_entry=1
+        shift;
+
+      h)
+        # Help&usage: -h 
+        print_help
+        exit
+        
       i)
-        # initialize the build environment
-        initialize_build_environment 
-        ;;
+        # Initialize the build environment in the default directory: -i
+        flag_init_build_env=1
+        shift;;
+
       I)
-        # initialize the build environment in a specific directory
-        initialize_build_environment "${OPTARG}"
-        ;;
+        # Initialize the build environment in a specific directory: -I <directory>
+        flag_init_build_env=1
+        arg_init_build_env="${OPTARG}"
+        shift 2;;
+
+      M)
+        # Create a new meta package: -M <package_name> <repo_name>
+        flag_new_meta_pkg=1
+        arg_new_meta_pkg="${OPTARG}"
+        shift 2;;
+
+      n)
+        # Create a new repository: -n <repo_name>
+        flag_new_repo=1
+        arg_new_repo="${OPTARG}"
+        shift 2;;
+      N)
+        # Create a new repository and open its config in vim: -N <repo_name>
+        flag_new_repo=1
+        arg_new_repo="${OPTARG}"
+        arg_open_config_in_editor=1
+        shift 2;;
+      
+      R)
+        # Remove a package: -R <package_name> <repo_name>
+        flag_remove=1
+        arg_remove="${OPTARG}"
+        shift 2;;
+
+      s)
+        # Sync all repositories: -s
+        flag_sync=1
+        shift;;
+
+      S)
+        # Sync a single repository: -S <repo_name>
+        flag_Sync=1
+        shift;;
+
+      u)
+        # Update all repositories: -u
+        flag_update=1
+        shift;;
+
+      U)
+        # Update a single repository: -U <repo_name>
+        flag_Update=1
+        shift;; 
+      
       *)
         print_usage
-        exit 1 ;;
+        exit 1 
+        ;;
+
     esac
   done
 
-  # case "$SUBCOMMAND" in
+  # trap remove_tmp_files EXIT
 
-  #   "help")
-  #     print_help $@
-  #     exit
-  #     ;;
+  # flags that are completely independent
+  if [[ ! -z "${flag_new_repo}" ]]; then
+    new_repository "${arg_new_repo}"
+  fi
 
-  #   "clone-repo"
+  if [[ ! -z "${flag_init_build_env}" ]]; then
+    initialize_build_environment "${arg_init_build_env}"
+  fi
 
-  # esac
+  # the cycle flag blocks other flags
+  if [[ ! -z "${flag_cycle}" ]]; then
+    # cycle
+    exit
+  fi
+
+  # flags that do not depend on a repository name
+  if [[ ! -z "${flag_sync}" ]]; then
+    sync_with_remote
+  fi
+
+  if [[ ! -z "${flag_update}" ]]; then
+    update_repository
+    echo
+  fi
+
+  if [[ ! -z "${flag_build_all}" ]]; then
+    build_all_packages
+  fi
+
+  # flags that depend on a repository name
+
+  local REPO="$1"; shift
+
+  if [[ -z "${REPO}" ]]; then
+    echo "No repository name specified."
+    exit 1
+  fi
+
+  if [[ ! -d "${GLOBAL_REPO_DIR}/${REPO}" ]]; then
+    echo "The repository ${REPO} does not exist."
+    exit 1
+  fi
+
+  if [[ ! -z "${flag_Sync}" ]]; then
+    sync_with_remote "${REPO}"
+  fi
+
+  if [[ ! -z "${flag_add}" ]]; then
+    add_package "${REPO}" "${arg_add}"
+  fi
+
+  if [[ ! -z "${flag_remove}" ]]; then
+    remove_package "${REPO}" "${arg_remove}"
+  fi
+
+  if [[ ! -z "${flag_Update}" ]]; then
+    update_repository "${REPO}"
+  fi
+
+  if [[ ! -z "${flag_build}" ]]; then
+    build_package "${REPO}" "${arg_build}"
+  fi
+
+  if [[ ! -z "${flag_new_meta_pkg}" ]]; then
+    # create_new_meta_package "${REPO}" "${arg_new_meta_pkg}"
+    echo
+  fi
+
 }
 
 main $@
